### ISSUE TITLE
Sportangebot von motor-mickten

### ISSUE THREAD

**Issue by Anna-Blume** [AfeefaDe/afeefa-neos#1606]
„Allerdings“ gibt es allerdings , so paradox das klingen mag, doch ein separates Flüchtlingssportangebot für „Kinder“ der EAE auf der Hamburger- sowie Bremerstraße. Dieses findet donnerstags statt. Betreut durch unseren Flüchtlingssportkoordinator Hagen Arnold  (BFD mit Flüchtlingsbezug). Ob dieses Sportangebot auf eurer Seite separat beworben werden soll kannst du unter: kindersport@motor-mickten.de erfragen.

**Comment by benjbk** [comment]
http://www.motor-mickten.de/verein/soziales-engagement/
