### ISSUE TITLE
Migrations- und Asylberatungsstellen in Dresden mit unseren abgleichen

### ISSUE THREAD

**Issue by Anna-Blume** [AfeefaDe/afeefa-neos#2058]
Migrations- und Asylberatungsstellen beraten vorwiegend zu folgenden Themen:
Deutschkurse /Integrationskurse, Wohnen, Gesundheit, Ehe/Familie, Schule und Beruf. Sie unterstützen beim Ausfüllen von
Anträgen und helfen bei der Beantwortung von Behördenbriefen.
http://www.dresden.de/de/leben/gesellschaft/migration/vereine/Beratung-und-Betreuung.php

**Comment by j-ohanna** [comment]
bis studentenwerk
