### ISSUE TITLE
[Netzwerk Asyl Migration Flucht] [Namf] Fwd: 26.04.2017, Dresden: Filmdokumentation und Gespräch „Viele habe ich erkannt – Gedächtnisprotokoll eines Kontraktarbeiters aus Hoyerswerda“

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-neos#2106]
- [ ] ...

Netzwerk Asyl Migration Flucht (namf@notraces.net) wrote:

`[Namf] Fwd: 26.04.2017, Dresden: Filmdokumentation und Gespräch „Viele habe ich erkannt – Gedächtnisprotokoll eines Kontraktarbeiters aus Hoyerswerda“`

```

```

**Comment by benjbk** [comment]
vorbei
