### ISSUE TITLE
[Netzwerk Asyl Migration Flucht] [Namf] Fwd: Kulturbüro Sachsen e.V. auf dem Evangelischen Kirchentag

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-neos#2109]
- [ ] ...

Netzwerk Asyl Migration Flucht (namf@notraces.net) wrote:

`[Namf] Fwd: Kulturbüro Sachsen e.V. auf dem Evangelischen Kirchentag`

```

```

**Comment by benjbk** [comment]
Kein Event in SN.
