### ISSUE TITLE
11. Juni Ungenutzte Gebäude in Dresden - Stadtrallye

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-neos#2135]
- [ ] ...

ashitaka (ashitaka@posteo.de) wrote:

`[Namf] Ungenutzte Gebäude in Dresden - Stadtrallye`

```
_______________________________________________
Namf mailing list
Namf@lists.notraces.net
https://lists.notraces.net/mailman/listinfo/namf

```

**Comment by Anna-Blume** [comment]
Ungenutzte Gebäude in Dresden - Stadtrallye - auch ein neuer Ort für Elixir?

Noch gibt es große leerstehende unsanierte Gebäude in Dresden, und es gibt Menschen, die selbstverwaltete Orte zum Wohnen und Leben schaffen wollen. Bringen wir beides zusammen!
Herzlich laden wir zur Stadtrallye am Sonntag, 11. Juni 2017 ein.  Nach gemeinsamem Frühstück um 11 Uhr am Wums e.V. besuchen und erkunden wir leerstehende Gebäude in verschiedenen Stadtteilen in kleinen Gruppen. Enden wollen wir gegen 16 Uhr, wenn alle Infos und Bilder zusammen getragen und Entdeckungen besprochen sind. Die dadurch entstehende Liste aktueller möglicher Freiräume ist ein Anfang für alle suchenden Projekte und Gruppen.

Wann: Samstag, 11. Juni 2017 um 11:00 Uhr
Wo: Wums e.V. , Columbusstr. 2, 01159 Dresden

https://www.facebook.com/events/1436768399719742
http://www.openstreetmap.org/way/27679051
https://www.wums.org/

Bitte bringt was fürs Bufett mit, für Getränke sorgen wir. Kommt gern per Rad, aber auch zu Fuß oder mit der Bahn ist es möglich.

Wir freuen uns auf euch!

Elixir Dresden

ps: …gern an Interessierte weiterversenden...

-- 
Elixir Dresden - Experimentierzentrum für interkulturelles Leben in Dresden
Frühlingstraße 14
01099 Dresden

kontakt@elixir-dresden.de
http://www.elixir-dresden.de
https://www.facebook.com/elixirdresden
Telefon: 01578-0356765
